// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcKdDGaqo8btDBnmlMDw_9gVGSsOTGAhY',
    appId: '1:959951852324:web:61e5340f308af2b8b819b1',
    messagingSenderId: '959951852324',
    projectId: 'to-do-list-9cadc',
    authDomain: 'to-do-list-9cadc.firebaseapp.com',
    storageBucket: 'to-do-list-9cadc.firebasestorage.app',
    measurementId: 'G-VKBJH7TFWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ7FOdhDXvhVIONdQ4x4KfhJA9GyrsoCY',
    appId: '1:959951852324:android:0610b73ad2d748aeb819b1',
    messagingSenderId: '959951852324',
    projectId: 'to-do-list-9cadc',
    storageBucket: 'to-do-list-9cadc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmUdDIJPRgdgDCrUSsYia0zNTJ7bqXuH0',
    appId: '1:959951852324:ios:471ebbc1cadf107db819b1',
    messagingSenderId: '959951852324',
    projectId: 'to-do-list-9cadc',
    storageBucket: 'to-do-list-9cadc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmUdDIJPRgdgDCrUSsYia0zNTJ7bqXuH0',
    appId: '1:959951852324:ios:471ebbc1cadf107db819b1',
    messagingSenderId: '959951852324',
    projectId: 'to-do-list-9cadc',
    storageBucket: 'to-do-list-9cadc.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcKdDGaqo8btDBnmlMDw_9gVGSsOTGAhY',
    appId: '1:959951852324:web:06f7daa8d29a886bb819b1',
    messagingSenderId: '959951852324',
    projectId: 'to-do-list-9cadc',
    authDomain: 'to-do-list-9cadc.firebaseapp.com',
    storageBucket: 'to-do-list-9cadc.firebasestorage.app',
    measurementId: 'G-2RGKH40VWP',
  );
}
